FROM postgres:<%= image.version %>-alpine
<%= snippet('labels', binding) -%>

ENV RUNUSER postgres
ENV HOME /postgresql
ENV PGDATA /postgresql/data

RUN apk add --no-cache \
        patch

<%= snippet('docker-entrypoint', binding) -%>

RUN mkdir /postgresql \
 && chown 0:0 /postgresql \
 && chmod 775 /postgresql

VOLUME /postgresql

RUN deluser postgres
